#spring.application.name=TaskManager
#server.port=${PORT:8080}
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/Task_Manager
#spring.datasource.username=postgres
#spring.datasource.password=IcyykWLlOmSdXOXZTMPgsQQhNbGxDFod psql -h tramway.proxy.rlwy.net -U postgres -p 44644 -d railway
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#spring.jpa.properties.hibernate.jdbc.time_zone=UTC
#
#jwt.secret=${JWT_SECRET:change-this-development-secret-change-this-development-secret}
#jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
#
#management.endpoints.web.exposure.include=health,info
#management.endpoint.health.probes.enabled=true
#
#server.servlet.context-path=/Task-Management
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.operationsSorter=method
#springdoc.swagger-ui.tagsSorter=alpha
#
#logging.level.org.springframework.security=INFO
#logging.level.org.hibernate.SQL=OFF

spring.application.name=TaskManager
server.port=${PORT:8080}

# ================= DATABASE CONFIG (RAILWAY) =================
spring.datasource.url=jdbc:postgresql://tramway.proxy.rlwy.net:44644/railway
spring.datasource.username=postgres
spring.datasource.password=IcyykWLlOmSdXOXZTMPgsQQhNbGxDFod
spring.datasource.driver-class-name=org.postgresql.Driver

# ================= JPA / HIBERNATE =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ================= JWT =================
jwt.secret=${JWT_SECRET:change-this-development-secret-change-this-development-secret}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# ================= ACTUATOR =================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

# ================= API CONFIG =================
server.servlet.context-path=/Task-Management

# ================= SWAGGER =================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# ================= LOGGING =================
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=OFF